  
model_params:
  model: Net


args:
  expdir: "."
  logdir: "log"

stages:

  data_params:
    batch_size: 256
    num_workers: 1

  state_params:
    num_epochs: 10
    main_metric: accuracy01
    minimize_metric: False
    checkpoint_data:
      exp: "thin is my best experiments"
      date: "today"

  criterion_params:
    criterion: CrossEntropyLoss

  callbacks_params:
    loss:
      callback: CriterionCallback
    optimizer:
      callback: OptimizerCallback
    accuracy:
      callback: AccuracyCallback
      accuracy_args: [1]
    saver:
      callback: CheckpointCallback

  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001
